/* Additional record code for Flowsheet generated by the OpenModelica Compiler v1.13.2 (64-bit). */

#include "meta/meta_modelica.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

